"""Feature columns expected by the Alzheimer prediction model."""

FEATURE_COLUMNS = [
    "roi_mean",
    "roi_std",
    "roi_median",
    "roi_min",
    "roi_max",
    "roi_p01",
    "roi_p05",
    "roi_p10",
    "roi_p25",
    "roi_p75",
    "roi_p90",
    "roi_p95",
    "roi_p99",
    "roi_iqr",
    "roi_range",
    "roi_energy",
    "roi_skew",
    "roi_kurtosis",
    "hippo_L_mm3",
    "hippo_R_mm3",
    "hippo_total_mm3",
    "brain_volume_mm3",
    "hippo_L_over_brain",
    "hippo_R_over_brain",
    "hippo_total_over_brain",
    "hippo_asymmetry_abs",
    "hippo_L_minus_R_over_total",
    "hippo_L_over_R",
    "hippo_R_over_L",
    "cnn_prob_AD",
    "cnn_pred_061",
]
